export const QUERY_KEYS = {
  FETCH_COURSES_PUBLIC: "FETCH_COURSES_PUBLIC",
  FETCH_COURSES: "FETCH_COURSES",
  FETCH_COURSE_SUMMARY: "FETCH_COURSE_SUMMARY",
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",

  FETCH_USER_COURSES: "FETCH_USER_COURSES",
  FETCH_USER: "FETCH_USER",
  FETCH_USER_SUMMARY: "FETCH_USER_SUMMARY",

  FETCH_ORDERS: "FETCH_ORDERS",
  FETCH_ORDER_SUMMARY: "FETCH_ORDER_SUMMARY",
  FETCH_ORDER_DETAIL: "FETCH_ORDER_DETAIL",
  CREATE_ORDER: "CREATE_ORDER",
  UPDATE_COUPON: "UPDATE_COUPON",
  FETCH_COUPON: "FETCH_COUPON",
  FETCH_COUPON_SUMMARY: "FETCH_COUPON_SUMMARY",
  GET_COUPON_CODE: "GET_COUPON_CODE",
  CREATE_COUPON: "CREATE_COUPON",
  DELETE_COUPON: "DELETE_COUPON",

  FETCH_RATING: "FETCH_RATING",
  FETCH_RATING_SUMMARY: "FETCH_RATING_SUMMARY",
  CREATE_RATING: "CREATE_RATING",
  UPDATE_RATING: "UPDATE_RATING",
  DELETE_RATING: "DELETE_RATING",

  FETCH_COMMENTS: "FETCH_COMMENTS",
  FETCH_COMMENT_SUMMARY: "FETCH_COMMENT_SUMMARY",
  CREATE_COMMENT: "CREATE_COMMENT",
  UPDATE_COMMENT: "UPDATE_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
} as const;
